import os
os.chdir(os.path.dirname(__file__))
with open('static/index.html','r',encoding='utf-8') as f:
    c=f.read()

# Replace conn-modal HTML with small popup like card-menu
old='<!-- ====== 连线详情模态框 ====== -->\n<div class="modal-overlay" id="conn-modal">\n    <div class="modal" style="width:340px;">\n        <h2>🔗 连线</h2>\n        <div class="detail-field">\n            <label>名称</label>\n            <input type="text" id="conn-name" placeholder="输入名称..." style="width:100%;padding:8px 10px;border-radius:6px;border:1px solid rgba(255,255,255,0.12);background:rgba(255,255,255,0.06);color:#eee;font-size:14px;outline:none;font-family:inherit;">\n        </div>\n        <div class="detail-field">\n            <label>字号 (10~30)</label>\n            <input type="number" id="conn-fontsize" value="14" min="10" max="30" style="width:80px;padding:8px 10px;border-radius:6px;border:1px solid rgba(255,255,255,0.12);background:rgba(255,255,255,0.06);color:#eee;font-size:14px;outline:none;">\n        </div>\n        <div class="detail-field">\n            <label>连线样式</label>\n            <div style="display:flex;gap:6px;flex-wrap:wrap;">\n                <button id="conn-arrow-none" onclick="setConnArrow(\'none\')" style="padding:6px 14px;border:none;border-radius:6px;font-size:12px;cursor:pointer;background:rgba(255,255,255,0.06);color:#aaa;font-family:inherit;">— 普通</button>\n                <button id="conn-arrow-single" onclick="setConnArrow(\'single\')" style="padding:6px 14px;border:none;border-radius:6px;font-size:12px;cursor:pointer;background:rgba(255,255,255,0.06);color:#aaa;font-family:inherit;">➡️ 单箭头</button>\n                <button id="conn-arrow-double" onclick="setConnArrow(\'double\')" style="padding:6px 14px;border:none;border-radius:6px;font-size:12px;cursor:pointer;background:rgba(255,255,255,0.06);color:#aaa;font-family:inherit;">↔️ 双箭头</button>\n            </div>\n        </div>\n        <div class="modal-actions">\n            <button class="btn-primary" onclick="saveConnDetail()" style="padding:8px 20px;border:none;border-radius:6px;font-size:13px;cursor:pointer;font-family:inherit;">💾 保存</button>\n            <button class="btn-action" onclick="closeConnModal()" style="padding:8px 20px;border:none;border-radius:6px;font-size:13px;cursor:pointer;color:#ccc;font-family:inherit;">关闭</button>\n            <button class="btn-danger" onclick="deleteConn()" style="padding:8px 20px;border:none;border-radius:6px;font-size:13px;cursor:pointer;margin-left:auto;font-family:inherit;">🗑️ 删除</button>\n        </div>\n    </div>\n</div>'

new='<!-- ====== 连线编辑浮窗 ====== -->\n<div id="conn-menu" style="display:none;position:fixed;z-index:3000;background:rgba(30,25,20,0.96);border:1px solid rgba(255,255,255,0.12);border-radius:8px;padding:8px;box-shadow:0 8px 30px rgba(0,0,0,0.5);backdrop-filter:blur(8px);min-width:160px;">\n    <input id="conn-name" placeholder="名称..." style="width:100%;padding:6px 8px;border-radius:4px;border:1px solid rgba(255,255,255,0.12);background:rgba(255,255,255,0.06);color:#eee;font-size:12px;outline:none;font-family:inherit;margin-bottom:6px;box-sizing:border-box;">\n    <div style="display:flex;gap:3px;margin-bottom:6px;flex-wrap:wrap;">\n        <button id="conn-arrow-none" onclick="setConnArrow(\'none\')" style="padding:4px 10px;border:none;border-radius:4px;font-size:11px;cursor:pointer;background:rgba(255,255,255,0.06);color:#aaa;font-family:inherit;">—</button>\n        <button id="conn-arrow-single" onclick="setConnArrow(\'single\')" style="padding:4px 10px;border:none;border-radius:4px;font-size:11px;cursor:pointer;background:rgba(255,255,255,0.06);color:#aaa;font-family:inherit;">➡️</button>\n        <button id="conn-arrow-double" onclick="setConnArrow(\'double\')" style="padding:4px 10px;border:none;border-radius:4px;font-size:11px;cursor:pointer;background:rgba(255,255,255,0.06);color:#aaa;font-family:inherit;">↔️</button>\n    </div>\n    <div style="display:flex;gap:3px;">\n        <button onclick="saveConnDetail()" style="padding:4px 12px;border:none;border-radius:4px;font-size:11px;cursor:pointer;background:#d4a87a;color:#1a1510;font-family:inherit;">💾</button>\n        <button onclick="deleteConn()" style="padding:4px 12px;border:none;border-radius:4px;font-size:11px;cursor:pointer;background:rgba(255,80,80,0.15);color:#ff6b6b;font-family:inherit;">🗑️</button>\n    </div>\n</div>'
c=c.replace(old,new)

# Update editConnectionLabel to position the popup like card-menu
old='function editConnectionLabel(conn) {\n    _editConnId = conn.id;\n    document.getElementById(\'conn-name\').value = conn.label || \'\';\n    document.getElementById(\'conn-fontsize\').value = conn.fontSize || 14;\n    [\'none\',\'single\',\'double\'].forEach(function(t) {\n        var btn = document.getElementById(\'conn-arrow-\' + t);\n        if (conn.arrowType === t) { btn.style.background = \'#d4a87a\'; btn.style.color = \'#1a1510\'; }\n        else { btn.style.background = \'rgba(255,255,255,0.06)\'; btn.style.color = \'#aaa\'; }\n    });\n    document.getElementById(\'conn-modal\').classList.add(\'active\');\n}'
new='function editConnectionLabel(conn) {\n    _editConnId = conn.id;\n    var m = document.getElementById(\'conn-menu\');\n    document.getElementById(\'conn-name\').value = conn.label || \'\';\n    [\'none\',\'single\',\'double\'].forEach(function(t) {\n        var btn = document.getElementById(\'conn-arrow-\' + t);\n        if (conn.arrowType === t) { btn.style.background = \'#d4a87a\'; btn.style.color = \'#1a1510\'; }\n        else { btn.style.background = \'rgba(255,255,255,0.06)\'; btn.style.color = \'#aaa\'; }\n    });\n    // position near the connection midpoint\n    var from = getPinPos(conn.fromId);\n    var to = getPinPos(conn.toId);\n    var mx = (from.x + to.x) / 2, my = (from.y + to.y) / 2;\n    var rect = container.getBoundingClientRect();\n    var sx = mx * state.scale + state.panX + rect.left;\n    var sy = my * state.scale + state.panY + rect.top;\n    m.style.left = Math.min(sx, window.innerWidth - 180) + \'px\';\n    m.style.top = Math.min(sy, window.innerHeight - 160) + \'px\';\n    m.style.display = \'block\';\n    setTimeout(function() { document.addEventListener(\'click\', closeConnMenu); }, 10);\n}'
c=c.replace(old,new)

# Update closeConnModal -> closeConnMenu
old='function closeConnModal() {\n    document.getElementById(\'conn-modal\').classList.remove(\'active\');\n}'
new='function closeConnMenu() {\n    var m = document.getElementById(\'conn-menu\');\n    if (m) m.style.display = \'none\';\n    document.removeEventListener(\'click\', closeConnMenu);\n}'
c=c.replace(old,new)

# Update saveConnDetail to use closeConnMenu
c=c.replace('closeConnModal();','closeConnMenu();')

# Update deleteConn
c=c.replace('closeConnModal();\n}\n\n','closeConnMenu();\n}\n\n')

with open('static/index.html','w',encoding='utf-8') as f:
    f.write(c)
print('ok')
